/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as TableauDeBordRouteImport } from './routes/tableau-de-bord'
import { Route as ParcoursIndexRouteImport } from './routes/parcours.index'
import { Route as ParcoursModuleIdIndexRouteImport } from './routes/parcours.$moduleId.index'
import { Route as ParcoursModuleIdLeconLessonIdRouteImport } from './routes/parcours.$moduleId.lecon.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauDeBordRoute = TableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoursIndexRoute = ParcoursIndexRouteImport.update({
  id: '/parcours/',
  path: '/parcours/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoursModuleIdIndexRoute = ParcoursModuleIdIndexRouteImport.update({
  id: '/parcours/$moduleId/',
  path: '/parcours/$moduleId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoursModuleIdLeconLessonIdRoute =
  ParcoursModuleIdLeconLessonIdRouteImport.update({
    id: '/parcours/$moduleId/lecon/$lessonId',
    path: '/parcours/$moduleId/lecon/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/parcours/': typeof ParcoursIndexRoute
  '/parcours/$moduleId/': typeof ParcoursModuleIdIndexRoute
  '/parcours/$moduleId/lecon/$lessonId': typeof ParcoursModuleIdLeconLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/parcours': typeof ParcoursIndexRoute
  '/parcours/$moduleId': typeof ParcoursModuleIdIndexRoute
  '/parcours/$moduleId/lecon/$lessonId': typeof ParcoursModuleIdLeconLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/parcours/': typeof ParcoursIndexRoute
  '/parcours/$moduleId/': typeof ParcoursModuleIdIndexRoute
  '/parcours/$moduleId/lecon/$lessonId': typeof ParcoursModuleIdLeconLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/tableau-de-bord'
    | '/parcours/'
    | '/parcours/$moduleId/'
    | '/parcours/$moduleId/lecon/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/tableau-de-bord'
    | '/parcours'
    | '/parcours/$moduleId'
    | '/parcours/$moduleId/lecon/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/connexion'
    | '/tableau-de-bord'
    | '/parcours/'
    | '/parcours/$moduleId/'
    | '/parcours/$moduleId/lecon/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnexionRoute: typeof ConnexionRoute
  TableauDeBordRoute: typeof TableauDeBordRoute
  ParcoursIndexRoute: typeof ParcoursIndexRoute
  ParcoursModuleIdIndexRoute: typeof ParcoursModuleIdIndexRoute
  ParcoursModuleIdLeconLessonIdRoute: typeof ParcoursModuleIdLeconLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau-de-bord': {
      id: '/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof TableauDeBordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours/': {
      id: '/parcours/'
      path: '/parcours'
      fullPath: '/parcours/'
      preLoaderRoute: typeof ParcoursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours/$moduleId/': {
      id: '/parcours/$moduleId/'
      path: '/parcours/$moduleId'
      fullPath: '/parcours/$moduleId/'
      preLoaderRoute: typeof ParcoursModuleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours/$moduleId/lecon/$lessonId': {
      id: '/parcours/$moduleId/lecon/$lessonId'
      path: '/parcours/$moduleId/lecon/$lessonId'
      fullPath: '/parcours/$moduleId/lecon/$lessonId'
      preLoaderRoute: typeof ParcoursModuleIdLeconLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnexionRoute: ConnexionRoute,
  TableauDeBordRoute: TableauDeBordRoute,
  ParcoursIndexRoute: ParcoursIndexRoute,
  ParcoursModuleIdIndexRoute: ParcoursModuleIdIndexRoute,
  ParcoursModuleIdLeconLessonIdRoute: ParcoursModuleIdLeconLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
